name: Dependency check - Build and Push Docker Image

on:
  schedule:
    - cron:  '0 0 * * *' 
  workflow_dispatch:
    # Needed so we can run it manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dependency_check_builder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            name/app
            ghcr.io/username/app            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw, value=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update Published Date
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          echo "Last Published: $(date)" > published.md
          git commit -am "published"
          git push origin main
